# Generated by Django 4.2 on 2023-04-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flights',
            name='time',
        ),
        migrations.AddField(
            model_name='flights',
            name='eta_date',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flights',
            name='eta_time',
            field=models.TimeField(default='00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flights',
            name='sh_date',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flights',
            name='sh_time',
            field=models.TimeField(default='00:00'),
            preserve_default=False,
        ),
    ]
